name: "CodeQL Advanced"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 0 * * 4'
jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
		runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: ${{ (matrix.language) }}
          build-mode: manual
